name: 'Publish All Modules'
description: 'Publishes all modules'
inputs:
  sonatype_user:
    description: 'Sonatype user'
    required: true
    default: ''
  sonatype_password:
    description: 'Sonatype password'
    required: true
    default: ''
  signing_key_id:
    description: 'Signing key id'
    required: true
    default: ''
  signing_key_password:
    description: 'Signing key password'
    required: true
    default: ''
  signing_key_file:
    description: 'Signing key file'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        ./gradlew --stacktrace clean publishToSonatype closeAndReleaseSonatypeStagingRepository
      shell: bash
      env:
        SONATYPE_NEXUS_USERNAME: ${{ inputs.sonatype_user }}
        SONATYPE_NEXUS_PASSWORD: ${{ inputs.sonatype_password }}
        SIGNING_KEY_ID: ${{ inputs.signing_key_id }}
        SIGNING_KEY_PASSWORD: ${{ inputs.signing_key_password }}
        SIGNING_KEY_FILE: ${{ inputs.signing_key_file }}
