name: Build
on: [pull_request, workflow_dispatch]

concurrency:
  group: build-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        codebase: [library, demo]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Only library assets are needed for the build step
      - name: Build with Gradle
        run: ./gradlew :${{ matrix.codebase }}:assemble

      - run: echo "Build status report=${{ job.status }}."
