name: Lint
on: [pull_request, workflow_dispatch]

concurrency:
  group: lint-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Lint
        run: ./gradlew ktLint
        continue-on-error: true

      - name: Get Lint Reports
        uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/reports/ktlint/*.xml
        continue-on-error: false
