name: Snapshot Release
on:
  workflow_dispatch: {}
env:
  SIGNING_KEY_FILE_PATH: /home/runner/secretKey.gpg

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/release-test.yml

  build:
    uses: ./.github/workflows/build.yml
    secrets:
      SIGNING_KEY_FILE: ${{ secrets.SIGNING_KEY_FILE }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

  # after build and unit tests are finished, publish all modules at once
  # to help reduce the probability of failure when interacting with sonatype servers
  release:
    name: Snapshot Release
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # pulls all commits (needed for semantic release to correctly version)
          fetch-depth: '0'
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Decode Signing Key
        uses: ./.github/actions/decode_signing_key_action
        with:
          signing_key_file: ${{ secrets.SIGNING_KEY_FILE }}
          signing_file_path: ${{ env.SIGNING_KEY_FILE_PATH }}

      - name: Set snapshot environment variable
        run: echo "USE_SNAPSHOT=true" >> $GITHUB_ENV

      - name: Install Semantic Release Dependencies
        run: npm install

      - name: GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@21

      - name: Publish to Maven
        uses: ./.github/actions/publish_all_modules
        with:
          sonatype_user: ${{ secrets.SONATYPE_SDKS_NEXUS_USERNAME }}
          sonatype_password: ${{ secrets.SONATYPE_SDKS_NEXUS_PASSWORD }}
          signing_key_id: ${{ secrets.SIGNING_SDKS_KEY_ID }}
          signing_key_password: ${{ secrets.SIGNING_SDKS_KEY_PASSWORD }}
          signing_key_file: ${{ env.SIGNING_SDKS_KEY_FILE_PATH }}
