name: Test
on: [pull_request, workflow_dispatch]

concurrency:
  group: test-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Dependencies
        run: echo "Install Dependencies"

      - name: Run Tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: false
