name: Test
on: [pull_request, workflow_dispatch]

concurrency:
  group: test-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest
        continue-on-error: false

      - name: Run Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
